### PR TITLE
Update runtime to 42

### PR DESCRIPTION
**Pull request by bbhtt**

### CODE REVIEW

**Comment by bbhtt** [comment]
bot, build

**Comment by Snaggly** [comment]
bot, build

**Comment by bbhtt** [comment]
bot, build

**Comment by bbhtt** [comment]
> Build [107841 failed](https://buildbot.flathub.org/#/builders/32/builds/107841)

https://github.com/Snaggly/PS2_Pnacher/issues/2

**Comment by bbhtt** [comment]
bot, build

**Pull request merged**
